i did
yura-gevorgyan/job-board pull request #3
Opened 2024-03-06 11:10 UTC by Vahagn-Movsisyan

1. Login/Registration
  2. Working with html pages
  3. Mail Verification
  4. Forgot password and my code ready to review

2024-03-06 11:46 UTC, Vahe650 commented on src/main/java/am/itspace/jobboard/config/SecurityConfig.java
> +                .requestMatchers("/login/page").permitAll()
.requestMatchers("/login/page", "/register/page").permitAll()

2024-03-06 11:46 UTC, Vahe650 commented on src/main/java/am/itspace/jobboard/config/SecurityConfig.java
> +                .requestMatchers("/register/page").permitAll()
remove this row

2024-03-06 11:46 UTC, Vahe650 commented on src/main/java/am/itspace/jobboard/config/SecurityConfig.java
> +                .anyRequest().permitAll()
.anyRequest().autenticated()

2024-03-06 11:49 UTC, Vahe650 commented on src/main/java/am/itspace/jobboard/controller/MainController.java
> +        return "index-04";
change name to "index";

2024-03-06 11:50 UTC, Vahe650 commented on src/main/java/am/itspace/jobboard/controller/UserController.java
> +    //We'll look at it later
add Todo
   
    //Todo We'll look at it later

2024-03-06 14:13 UTC, LyovaHakobyan requested changes

2024-03-06 14:13 UTC, LyovaHakobyan commented on src/main/java/am/itspace/jobboard/config/SecurityConfig.java
> +                .requestMatchers("/").permitAll()
These methodes are depricated, use instead of them`

httpSecurity.csrf(AbstractHttpConfigurer::disable)

                .authorizeHttpRequests(authorizeHttpRequests -> authorizeHttpRequests
                        .requestMatchers("---").permitAll()
                        .requestMatchers("---").permitAll()
                        ......
                )
                  .formLogin(formLogin -> formLogin
                          .loginPage("---")
                          .....
                  )
                .logout(logout -> logout
                        .logoutUrl("---")
                        ....
                );

2024-03-06 14:13 UTC, LyovaHakobyan commented on src/main/java/am/itspace/jobboard/config/SecurityConfig.java
> +                .requestMatchers("/login/page").permitAll()
Change login and register requestMatchers, make them`

.requestMatchers("/login/**").anonymous()
and
.requestMatchers("/register/**").anonymous()

2024-03-06 14:13 UTC, LyovaHakobyan commented on src/main/java/am/itspace/jobboard/controller/UserController.java
> +    @GetMapping("/login/page")
delete "page" word, make  @GetMapping("/login")

2024-03-06 14:13 UTC, LyovaHakobyan commented on src/main/java/am/itspace/jobboard/controller/UserController.java
> +    @GetMapping("/confirm/email/page")
make  @GetMapping("/login/confirm/email")

2024-03-06 14:13 UTC, LyovaHakobyan commented on src/main/java/am/itspace/jobboard/controller/UserController.java
> +    @GetMapping("/confirm/email/change/for/password/page")
make @GetMapping("/login/confirm/email/change/for/password")

2024-03-06 14:13 UTC, LyovaHakobyan commented on src/main/java/am/itspace/jobboard/controller/UserController.java
> +    @GetMapping("/forgot/password/page")
delete word "page"

2024-03-06 14:13 UTC, LyovaHakobyan commented on src/main/java/am/itspace/jobboard/controller/UserController.java
> +    @GetMapping("/change/password/page")
delete word "page"

2024-03-06 14:13 UTC, LyovaHakobyan commented on src/main/java/am/itspace/jobboard/controller/UserController.java
> +    @GetMapping("/register/page")
delete word "page"

2024-03-09 15:20 UTC, Vahe650 approved these changes

2024-03-10 17:55 UTC, merged